// Generated by gencpp from file krti18/Mission.msg
// DO NOT EDIT!


#ifndef KRTI18_MESSAGE_MISSION_H
#define KRTI18_MESSAGE_MISSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krti18
{
template <class ContainerAllocator>
struct Mission_
{
  typedef Mission_<ContainerAllocator> Type;

  Mission_()
    : mission_type(0)  {
    }
  Mission_(const ContainerAllocator& _alloc)
    : mission_type(0)  {
  (void)_alloc;
    }



   typedef int8_t _mission_type_type;
  _mission_type_type mission_type;





  typedef boost::shared_ptr< ::krti18::Mission_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krti18::Mission_<ContainerAllocator> const> ConstPtr;

}; // struct Mission_

typedef ::krti18::Mission_<std::allocator<void> > Mission;

typedef boost::shared_ptr< ::krti18::Mission > MissionPtr;
typedef boost::shared_ptr< ::krti18::Mission const> MissionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krti18::Mission_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krti18::Mission_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace krti18

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'krti18': ['/home/ubuntu/Documents/auav/palapa707/src/krti18/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::krti18::Mission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krti18::Mission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krti18::Mission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krti18::Mission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krti18::Mission_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krti18::Mission_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krti18::Mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9afd8c5819bc00a1915a5527b744824a";
  }

  static const char* value(const ::krti18::Mission_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9afd8c5819bc00a1ULL;
  static const uint64_t static_value2 = 0x915a5527b744824aULL;
};

template<class ContainerAllocator>
struct DataType< ::krti18::Mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krti18/Mission";
  }

  static const char* value(const ::krti18::Mission_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krti18::Mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 mission_type\n\
";
  }

  static const char* value(const ::krti18::Mission_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krti18::Mission_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mission_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krti18::Mission_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krti18::Mission_<ContainerAllocator>& v)
  {
    s << indent << "mission_type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mission_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRTI18_MESSAGE_MISSION_H
