// Generated by gencpp from file krti18/State.msg
// DO NOT EDIT!


#ifndef KRTI18_MESSAGE_STATE_H
#define KRTI18_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krti18
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : doing_mission(false)  {
    }
  State_(const ContainerAllocator& _alloc)
    : doing_mission(false)  {
  (void)_alloc;
    }



   typedef uint8_t _doing_mission_type;
  _doing_mission_type doing_mission;





  typedef boost::shared_ptr< ::krti18::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krti18::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::krti18::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::krti18::State > StatePtr;
typedef boost::shared_ptr< ::krti18::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krti18::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krti18::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace krti18

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'krti18': ['/home/ubuntu/Documents/auav/palapa707/src/krti18/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::krti18::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krti18::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krti18::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krti18::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krti18::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krti18::State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krti18::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c407ee5aa6ad97a1ae9cb0ab26cc8f29";
  }

  static const char* value(const ::krti18::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc407ee5aa6ad97a1ULL;
  static const uint64_t static_value2 = 0xae9cb0ab26cc8f29ULL;
};

template<class ContainerAllocator>
struct DataType< ::krti18::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krti18/State";
  }

  static const char* value(const ::krti18::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krti18::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool doing_mission\n\
";
  }

  static const char* value(const ::krti18::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krti18::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.doing_mission);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krti18::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krti18::State_<ContainerAllocator>& v)
  {
    s << indent << "doing_mission: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.doing_mission);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRTI18_MESSAGE_STATE_H
